from requests import post

ont_id = input("ID: ")
if ont_id == "":
    ont_id = "AutoGeneratedID"
sn = input("SN: ")
e9 = "virtualOLT"
acct = input("Acct: ")
ont_prof = input("Profile: ")

payload = {
    "ont-id": ont_id,
    "ont-type": "Residential",
    "isGlobalOnt": True,
    "serial-number": sn,
    "subscriber-id": acct,
    "ont-profile-id": ont_prof,
}

ont = post(
    f"https://10.20.7.10:18443/rest/v1/config/device/{e9}/ont",
    auth=("admin", "Thesearethetimes!"),
    verify=False,
    json=payload,
)

print(ont.json())
if ont.status_code == 200:
    print(f"\nONT created successfully!")
else:
    print(ont.json())
