from requests import post

ont_id = input("ID: ")
if ont_id == "ag":
    ont_id = "AutoGeneratedID"
sn = input("SN: ")
e9 = input("E9: ")
acct = input("Acct: ")

payload = {
    "ont-id": ont_id,
    "ont-type": "Residential",
    "isGlobalOnt": False,
    "serial-number": sn,
    "device-name": e9,
    "subscriber-id": acct,
    "ont-profile-id": "GP1100X",
}

ont = post(
    f"https://10.20.7.10:18443/rest/v1/config/device/{e9}/ont",
    auth=("admin", "Thesearethetimes!"),
    verify=False,
    json=payload,
)
if ont.status_code == 200:
    print(f"\nONT created successfully!")
